# ! 原文件为 xml 文件，但由于 xml 文件不太好注释，更改为 yaml 文件，使用 yaml 文件注释

{
    # 基本控制参数
    "type": "OSC_POSE", # 控制器类型：操作空间位姿控制（同时控制位置和姿态）

    "input_max": 1, # 输入最大值：控制器接收的动作输入的最大值（归一化范围）
    "input_min": -1, # 输入最小值：控制器接收的动作输入的最小值（归一化范围）

    #   [x_max, y_max, z_max, roll_max, pitch_max, yaw_max] (单位：米, 弧度)
    "output_max": [0.05, 0.05, 0.05, 0.5, 0.5, 0.5], # 输出的最大变化量限制
    "output_min": [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5], # 输出的最小变化量限制（负值表示反向运动）

    # 控制器增益参数
    "kp": 150, # 位置增益：控制器响应误差的强度，数值越大响应越快但可能导致振荡。可以是标量（所有控制器维度的相同值），也可以是列表（每个维度的具体值）
    "damping_ratio": 1, # 阻尼比常数：控制系统的阻尼特性，1表示临界阻尼（无超调），<1欠阻尼（有振荡），>1过阻尼（响应慢），影响运动的平滑性和稳定性
    "impedance_mode": "fixed", # 阻抗模式：比例增益的可调整范围, 允许在线调节 kp 值的边界，可选项有 fixed(固定增益), variable(可变增益), variable_kp(仅kp可变)

    # ! 以下两个仅在 impedance_mode 设置为 variable 或 variable_kp 时才有效
    # 可变阻抗模式的限制范围（仅在impedance_mode为variable或variable_kp时有效）
    "kp_limits": [0, 300], # kp的允许范围：[最小值, 最大值]
    "damping_ratio_limits": [0, 10], # 阻尼比的允许范围：[最小值, 最大值]。

    # 位置和姿态限制
    "position_limits": null, # 位置限制：[min_pos, max_pos]，null表示无限制
    "orientation_limits": null, # 姿态限制：[min_ori, max_ori]，null表示无限制

    # 控制策略参数
    "uncouple_pos_ori": true, # 解耦位置和姿态控制：true表示位置和姿态独立控制，false表示耦合。只对 OSC_POSE 有效。
    # * 在 robosuite 的增量控制中，计算不是基于[全量程]的比例，而是基于[从中性点（0）向两端发散]的比例。
    # * 标准公式（线性缩放）：输入/输出 = 输入最大值/输出最大值。因为在控制器眼里，0 才是起点，如果输入是正数，往正方向动；如果是负数，往负方向动。即：以 "0" 为界，进行比例缩放！！！
    # ! 线性重映射（Linear Remapping） 或 区间映射：(Output - C）/(D - C) =  (Input - A)/(B - A), 其中 输入区间 [A, B] = [-1, 1]，输出区间 [C, D] = [-0.05, 0.05]，待输入值 Input = 0.1
    # 如果按照全量程比例计算，输入 0 可能会对应一个非零的物理位移（除非你手动偏移），这会让 AI 非常难以控制机器人的静止状态。
    "control_delta": true, # 增量控制：true 表示控制增量（相对当前位置），false 表示控制绝对位置。仅适用于 OSC_POSE 或 OSC_POSITION 控制器。若改成 False，则机器人的运动轨迹会变得非常暴力和大幅度，会“失控”

    # 插值参数
    "interpolation": null, # 插值方式，null 表示不使用插值，"linear"表示线性插值。目前只支持 "linear"。
    # 举例：如果 ramp_ratio 设为 0.2，意味着动作的前 20% 时间在匀加速，中间 60% 匀速，后 20% 匀减速（类似于梯形速度规划）。这能有效保护机械臂的减速器，防止急停造成的晃动。
    "ramp_ratio": 0.2, # 斜坡比例：用于平滑动作过渡，值越小过渡越平缓。即：控制器开始时逐渐增加输出，避免突然的大动作。如果使用线性插值，指定执行插值命令的分配时间步（值从[0， 1]）的比例。
}
